### ISSUE TITLE
Uncaught TypeError: Cannot read property 'r' of undefined

### ISSUE THREAD

**Issue by erikLundstedt** [Hyftar/keyboard-heatmap#5]
[Enter steps to reproduce:]

1. install and enable the pakage
1,5. ctrl-alt-h to toggle the heatmap
2. go to a textfile
3. press a key

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Education
**Thrown From**: [keyboard-heatmap](https://github.com/hyftar/keyboard-heatmap) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'r' of undefined

```
At C:\Users\elev\.atom\packages\keyboard-heatmap\lib\color-gradient-helper.js:20

TypeError: Cannot read property 'r' of undefined
    at transitionBetween (/packages/keyboard-heatmap/lib/color-gradient-helper.js:20:30)
    at Object.selectColor (/packages/keyboard-heatmap/lib/color-gradient-helper.js:38:12)
    at KeyboardHeatmapView.updateUI (/packages/keyboard-heatmap/lib/keyboard-heatmap-view.js:51:42)
    at /packages/keyboard-heatmap/lib/keyboard-heatmap.js:67:42)
```

### Commands

```
     -3:27.3.0 core:paste (input.hidden-input)
     -3:27 editor:newline (input.hidden-input)
     -3:26.9.0 intentions:highlight (input.hidden-input)
     -3:26.7.0 core:paste (input.hidden-input)
     -3:26.4.0 editor:newline (input.hidden-input)
     -3:26.3.0 intentions:highlight (input.hidden-input)
     -3:26.2.0 core:paste (input.hidden-input)
     -3:25.8.0 editor:newline (input.hidden-input)
     -3:25.7.0 intentions:highlight (input.hidden-input)
     -3:25.6.0 core:paste (input.hidden-input)
 40x -3:24.6.0 core:move-up (input.hidden-input)
  2x -3:08.4.0 intentions:highlight (input.hidden-input)
  2x -2:49.2.0 core:backspace (input.hidden-input)
     -0:41 keyboard-heatmap:toggleView (div.package-detail.panels-item)
     -0:37.8.0 keyboard-heatmap:toggleKeyLogger (div.package-detail.panels-item)
  3x -0:25.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
achievements 0.9.0 
aligner-php 1.2.0 
alignment 1.1.5 
arduino-toolbelt 0.1.1 
atom-css-comb 3.3.1 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-name-that-color 0.2.1 
atom-sort-sass 0.2.1 
Atom-Syntax-highlighting-for-Sass 0.5.0 
atom-toolbar 0.1.6 
autocomplete-computercraft 1.0.0 
autocomplete-lua 0.9.1 
block-comment 0.4.3 
busy-signal 1.4.3 
color-picker 2.3.0 
comment 0.6.1 
css-snippets 1.1.0 
fold-comments 0.6.0 
gitkraken-glo 1.0.1 
html-nested-comments 3.4.0 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-php 0.7.15 
increment-me 0.4.1 
intentions 1.1.5 
json-colorer 1.0.0 
keyboard-heatmap 0.1.0 
language-computercraft 0.2.1 
language-lua 0.9.11 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
live-code-runner 5.3.0 
markdown-toolbar 0.1.2 
minimap 4.29.9 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
p5js-toolbar 0.1.7 
php-server 0.8.0 
pigments 0.40.2 
sass-comment 1.4.0 
tool-bar 1.1.10 
tool-bar-almighty 0.8.2 
web-view 3.0.0 
word-art-comments 0.4.0 
```

**Comment by Hyftar** [comment]
Thank-you for your contribution. While I work on resolving the issue, please note that you first have to turn on the keylogger using <kbd>cmd</kbd> + <kbd>alt</kbd> + <kbd>k</kbd> before displaying the results.
